# This file and all contents in it are OPTIONAL.

# The namespace this chart will be installed and restricted to,
# if not specified the chart will be installed to "default"
namespace: fleet-helm-example

# Custom helm options
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: fleet-blackbox

  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: "prometheus-blackbox-exporter"

  # An https to a valid Helm repository to download the chart from
  repo: "https://charts.helm.sh/stable"

  # Used if repo is set to look up the version of the chart
  version: ""

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 0

  # Custom values that will be passed as values.yaml to the installation
  values:
    serviceMonitor:
      enabled: true
      targets:
        - name: example_fleet                    # Human readable URL that will appear in Prometheus / AlertManager
          url: https://atp879.cloudport.amagi.tv/  # The URL that blackbox will scrape
          interval: 15s                    # Scraping interval. Overrides value set in `defaults`
          scrapeTimeout: 15s               # Scrape timeout. Overrides value set in `defaults`
          module: http_2xx
        - name: loki_fleet                 # Human readable URL that will appear in Prometheus / AlertManager
          url: https://prom.cloudport.amagi.tv/  # The URL that blackbox will scrape
          interval: 35s                   # Scraping interval. Overrides value set in `defaults`
          scrapeTimeout: 35s               # Scrape timeout. Overrides value set in `defaults`
          module: http_2xx
